version: "0.2"
ignorePaths:
  - go.mod
  - go.sum,
  - .trunk/**
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - SASL
  - cafile
  - olekukonko
  - sarama
  - unconvert
  - golangci
  - karancode
  - justfile
  - gomod
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - gofumpt
  - aaronjheng
  - dotenv
  - compinit
  - tablewriter
  - mapstructure
  - adrg
  - localmodule
import: []
