linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    - gofumpt
    - gci

linters-settings:
  gofmt:
    simplify: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/aaronjheng/kafka-cli)
    custom-order: true
